#define port for API gateway
server:
  port: 8085

spring:
  application:
    name: API Gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: productservice
              uri: lb://productservice
              predicates:
                - Path=/products/**
#To register eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


